apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: k-s-sea
build:
  artifacts:
  - image: pirates
    context: src/pirates
    docker:
      dockerfile: Dockerfile
  - image: sea
    context: src/sea
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - pirates-kubernetes/base/pirates-deploy.yaml
    - pirates-kubernetes/base/pirates-svc.yaml
    - sea-kubernetes/base/sea-deploy.yaml
    - sea-kubernetes/base/sea-svc.yaml